export const IMAGES = {
  LOGO: require('./second.png'),
  GOOGLE: require('./google.png'),
  EQUIPMENT: require('./equipment.png'),
  PROFILE: require('./man.png'),
  ADDRESS: require('./address1.png'),
  DELETE: require('./delete.png'),
  EDIT: require('./edit.png'),
  DOTS: require('./dots.png'),
  HEART: require('./heart.png'),
  COUPON: require('./coupon.png'),
  WALLET: require('./wallet.png'),
  ORDER: require('./order.png'),
  ADD: require('./add.png'),
  CART: require('./trolley.png'),
  HOME: require('./home.png'),
  USER: require('./user.png'),
  CATEGORIES: require('./grid.png'),
  FIRST: require('./first.jpg'),
  SECOND: require('./second.png'),
};
