import {
  FadeIn,
  FadeInRight,
  FadeInLeft,
  FadeInUp,
  FadeInDown,
  FlipInEasyX,
  FlipInEasyY,
  FlipInXDown,
  FlipInXUp,
  FlipInYLeft,
  FlipInYRight,
  SlideInRight,
  SlideInLeft,
  SlideInUp,
  SlideInDown,
  ZoomIn,
  ZoomInDown,
  ZoomInEasyDown,
  ZoomInEasyUp,
  ZoomInLeft,
  ZoomInRight,
  ZoomInRotate,
  ZoomInUp,
  BounceIn,
  BounceInRight,
  BounceInLeft,
  BounceInUp,
  BounceInDown,
  LightSpeedInRight,
  LightSpeedInLeft,
  PinwheelIn,
  RollInRight,
  RollInLeft,
  RotateInDownLeft,
  RotateInDownRight,
  RotateInUpLeft,
  RotateInUpRight,
  StretchInX,
  StretchInY,
} from 'react-native-reanimated';

export const AnimationsIn = [
  FadeIn,
  FadeInRight,
  FadeInLeft,
  FadeInUp,
  FadeInDown,
  FlipInEasyX,
  FlipInEasyY,
  FlipInXDown,
  FlipInXUp,
  FlipInYLeft,
  FlipInYRight,
  SlideInRight,
  SlideInLeft,
  SlideInUp,
  SlideInDown,
  ZoomIn,
  ZoomInDown,
  ZoomInEasyDown,
  ZoomInEasyUp,
  ZoomInLeft,
  ZoomInRight,
  ZoomInRotate,
  ZoomInUp,
  BounceIn,
  BounceInRight,
  BounceInLeft,
  BounceInUp,
  BounceInDown,
  LightSpeedInRight,
  LightSpeedInLeft,
  PinwheelIn,
  RollInRight,
  RollInLeft,
  RotateInDownLeft,
  RotateInDownRight,
  RotateInUpLeft,
  RotateInUpRight,
  StretchInX,
  StretchInY,
];

export const productAnimations = [BounceIn, FadeIn];

export const detailCardAnimations = [LightSpeedInRight, LightSpeedInLeft];
